name = "prisma-hyperdrive-joel-23367"
main = "src/index.ts"
compatibility_date = "2024-05-04"
node_compat = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "4e74104320c64e72ba2c9d32f3b97f2a"
# Add the following line if you want to try things locally (without Hyperdrive)
# localConnectionString = "postgresql://..."
